# Generated by Django 5.0.14 on 2025-06-03 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0005_merge_branches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='declaracion',
        ),
        migrations.RemoveField(
            model_name='historicaldocumento',
            name='declaracion',
        ),
    ]
