# Generated by Django 5.1 on 2025-12-29 23:00

from django.db import migrations


class Migration(migrations.Migration):
    """
    Merge migration to resolve parallel branches at 0003-0004 level.
    
    Two branches existed after 0002:
    Branch A: 0003_auto_20250603_1609 → 0004_documento_content_type...
    Branch B: 0003_gastosextra → 0004_rename_decripcion_gastosextra_descripcion
    
    This migration merges them before they continue.
    """

    dependencies = [
        ('importaciones', '0004_documento_content_type_documento_object_id_and_more'),
        ('importaciones', '0004_rename_decripcion_gastosextra_descripcion'),
    ]

    operations = [
        # No operations needed - this is just to merge the branches
    ]
