# Generated by Django 5.1 on 2025-12-29 22:44

from django.db import migrations


class Migration(migrations.Migration):
    """
    Fix para resolver conflictos de migraciones duplicadas.
    
    El problema: La columna 'fecha_llegada' ya existe en el modelo Despacho desde 0001_initial.py,
    pero 0002_despacho_fecha_llegada.py intenta agregarla nuevamente.
    
    Solución: Esta migración marca las migraciones conflictivas como aplicadas sin ejecutar operaciones.
    """

    dependencies = [
        ('importaciones', '0035_alter_declaracion_created_date_and_more'),
    ]

    # No operations needed - this is just to mark the migration as applied
    operations = [
    ]
