# Generated by Django 5.1 on 2025-12-29 23:03

from django.db import migrations


class Migration(migrations.Migration):
    """
    Comprehensive fix for migration conflicts.
    
    Problem: Multiple parallel migration branches existed from 0003-0011,
    caused by development in parallel Git branches.
    
    Solution:
    1. Removed duplicate 0002_despacho_fecha_llegada.py (fecha_llegada already in 0001_initial.py)
    2. Updated 0003_gastosextra to depend on 0002_tipodocumento instead of deleted migration
    3. Created 0005_merge_branches to merge the 0004 branch split
    4. Updated 0005 migrations to depend on the merge
    5. Existing 0013_merge_20250627_0250.py handles later merges (0011-0012)
    
    All schema changes are already applied through the existing migrations.
    This migration just documents the resolution.
    """

    dependencies = [
        ('importaciones', '0035_alter_declaracion_created_date_and_more'),
    ]

    operations = [
        # No database operations needed
        # All schema changes already exist in previous migrations
    ]

