# Generated by Django 5.1 on 2025-12-30 14:15

from django.db import migrations


class Migration(migrations.Migration):
    """
    Fix para InconsistentMigrationHistory sin modificar el grafo existente.
    
    PROBLEMA:
    Las migraciones fueron aplicadas en un orden diferente al esperado.
    
    SOLUCIÓN - Elige UNA opción:
    
    ═══════════════════════════════════════════════════════════════════
    OPCIÓN 1: Fake Migration (RECOMENDADA - Más Simple)
    ═══════════════════════════════════════════════════════════════════
    
    python manage.py migrate importaciones 0036 --fake
    python manage.py migrate importaciones
    python manage.py test
    
    Esto sincroniza el tracking de Django sin modificar el schema.
    
    ═══════════════════════════════════════════════════════════════════
    OPCIÓN 2: SQLite para Tests (Para evitar problemas con MySQL)
    ═══════════════════════════════════════════════════════════════════
    
    # Agregar en settings.py:
    import sys
    if 'test' in sys.argv:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': ':memory:',
            }
        }
    
    Luego: python manage.py test
    
    ═══════════════════════════════════════════════════════════════════
    OPCIÓN 3: Limpiar Base de Datos de Test
    ═══════════════════════════════════════════════════════════════════
    
    DROP DATABASE IF EXISTS test_semilla360;
    CREATE DATABASE test_semilla360;
    python manage.py migrate
    python manage.py test
    
    ═══════════════════════════════════════════════════════════════════
    
    NOTA: La columna 'fecha_llegada' ya existe en tu base de datos.
    No se requieren cambios de schema, solo sincronizar el tracking.
    
    Para más detalles, ver: SOLUCION_MIGRACIONES.md
    """

    dependencies = [
        ('importaciones', '0036_fix_duplicate_migrations'),
    ]

    operations = [
        # Migración vacía - solo documentación
    ]
