# Generated by Django 6.0 on 2025-12-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0037_fix_inconsistent_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionesPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Permiso de Importaciones',
                'verbose_name_plural': 'Permisos de Importaciones',
                'permissions': [('can_manage_importaciones', 'Puede gestionar importaciones (DUA, declaraciones, proveedores)'), ('can_view_importaciones', 'Puede ver información de importaciones'), ('can_view_importaciones_reports', 'Puede ver reportes de importaciones'), ('can_manage_documents', 'Puede gestionar documentos de importaciones'), ('can_view_documents', 'Puede ver documentos de importaciones')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.AlterField(
            model_name='despacho',
            name='archivo_pdf',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
