# Generated by Django 6.0 on 2025-12-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_direccion_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Permiso de Usuarios',
                'verbose_name_plural': 'Permisos de Usuarios',
                'permissions': [('can_manage_users', 'Puede gestionar usuarios (crear, editar, eliminar)'), ('can_view_users', 'Puede ver usuarios'), ('can_manage_roles', 'Puede gestionar roles y permisos'), ('can_view_roles', 'Puede ver roles y permisos')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
