# Generated by Django 5.2.5 on 2026-01-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0007_alter_almacenpermissions_options'),
        ('usuarios', '0010_mantenimientopermissions_proveedorpermissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserprofile',
            name='require_sede_access',
            field=models.BooleanField(default=False, help_text='Si True, el usuario solo puede acceder a sedes asignadas explícitamente', verbose_name='Requiere Acceso a Sede'),
        ),
        migrations.AddField(
            model_name='historicaluserprofile',
            name='require_warehouse_access',
            field=models.BooleanField(default=False, help_text='Si True, el usuario solo puede acceder a almacenes asignados explícitamente', verbose_name='Requiere Acceso a Almacén'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='almacenes_asignados',
            field=models.ManyToManyField(blank=True, help_text='Almacenes a los que el usuario tiene acceso', related_name='usuarios_asignados', to='almacen.almacen', verbose_name='Almacenes Asignados'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='require_sede_access',
            field=models.BooleanField(default=False, help_text='Si True, el usuario solo puede acceder a sedes asignadas explícitamente', verbose_name='Requiere Acceso a Sede'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='require_warehouse_access',
            field=models.BooleanField(default=False, help_text='Si True, el usuario solo puede acceder a almacenes asignados explícitamente', verbose_name='Requiere Acceso a Almacén'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sedes_asignadas',
            field=models.ManyToManyField(blank=True, help_text='Sedes/direcciones a las que el usuario tiene acceso', related_name='usuarios_asignados', to='usuarios.direccion', verbose_name='Sedes Asignadas'),
        ),
    ]
