# Generated by Django 5.2.5 on 2025-12-18 15:46

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_legacymovalmcab_cadirenv'),
        ('importaciones', '0035_alter_declaracion_created_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRegistroEstibaje',
            fields=[
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('fecha_registro', models.DateTimeField(blank=True, editable=False)),
                ('tipo_documento', models.CharField(choices=[('NI', 'Nota de Ingreso'), ('GS', 'Guía de Salida'), ('OT', 'Otro')], max_length=2)),
                ('nro_documento', models.CharField(help_text='Número o Serie-Número del ERP', max_length=50)),
                ('transportista', models.CharField(blank=True, help_text='Razón social del transportista', max_length=200, null=True)),
                ('placa_vehiculo', models.CharField(blank=True, max_length=20, null=True)),
                ('total_sacos_procesados', models.IntegerField(default=0)),
                ('costo_total_operacion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('creado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='importaciones.empresa')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Registro de Estibaje',
                'verbose_name_plural': 'historical Registros de Estibaje',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTipoEstibaje',
            fields=[
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('tarifa_por_saco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('empresa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='importaciones.empresa')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Tipo de Estibaje',
                'verbose_name_plural': 'historical Tipos de Estibaje',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RegistroEstibaje',
            fields=[
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('tipo_documento', models.CharField(choices=[('NI', 'Nota de Ingreso'), ('GS', 'Guía de Salida'), ('OT', 'Otro')], max_length=2)),
                ('nro_documento', models.CharField(help_text='Número o Serie-Número del ERP', max_length=50)),
                ('transportista', models.CharField(blank=True, help_text='Razón social del transportista', max_length=200, null=True)),
                ('placa_vehiculo', models.CharField(blank=True, max_length=20, null=True)),
                ('total_sacos_procesados', models.IntegerField(default=0)),
                ('costo_total_operacion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_estibaje', to='importaciones.empresa')),
            ],
            options={
                'verbose_name': 'Registro de Estibaje',
                'verbose_name_plural': 'Registros de Estibaje',
            },
        ),
        migrations.CreateModel(
            name='TipoEstibaje',
            fields=[
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('tarifa_por_saco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_estibaje', to='importaciones.empresa')),
            ],
            options={
                'verbose_name': 'Tipo de Estibaje',
                'verbose_name_plural': 'Tipos de Estibaje',
            },
        ),
        migrations.CreateModel(
            name='HistoricalDetalleEstibaje',
            fields=[
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('cantidad_sacos', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Tarifa aplicada', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('registro', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='almacen.registroestibaje')),
                ('tipo_estibaje', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='almacen.tipoestibaje')),
            ],
            options={
                'verbose_name': 'historical Detalle de Estibaje',
                'verbose_name_plural': 'historical Detalles de Estibaje',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DetalleEstibaje',
            fields=[
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_sacos', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Tarifa aplicada', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='almacen.registroestibaje')),
                ('tipo_estibaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almacen.tipoestibaje')),
            ],
            options={
                'verbose_name': 'Detalle de Estibaje',
                'verbose_name_plural': 'Detalles de Estibaje',
            },
        ),
        migrations.AddConstraint(
            model_name='registroestibaje',
            constraint=models.UniqueConstraint(fields=('empresa', 'tipo_documento', 'nro_documento'), name='unique_estibaje_documento_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='tipoestibaje',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='unique_tipo_estibaje_empresa'),
        ),
    ]
