# Generated by Django 5.2.5 on 2025-12-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0004_historicalregistroestibaje_historicaltipoestibaje_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalregistroestibaje',
            name='transportista',
        ),
        migrations.RemoveField(
            model_name='registroestibaje',
            name='transportista',
        ),
        migrations.AddField(
            model_name='historicalregistroestibaje',
            name='producto_nombre',
            field=models.CharField(blank=True, help_text='Ej: Torta de Soya Hi Pro', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalregistroestibaje',
            name='transportista_nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalregistroestibaje',
            name='transportista_ruc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicaltipoestibaje',
            name='accion',
            field=models.CharField(choices=[('CARGA', 'Carga (Salida de Almacén al Camión)'), ('DESCARGA', 'Descarga (Ingreso del Camión al Piso/Almacén)'), ('TRASBORDO', 'Trasbordo (De Camión a Camión directo)'), ('REESTIBA', 'Reestiba (Mover dentro del mismo camión/almacén)'), ('OTRO', 'Otros Servicios')], default='DESCARGA', help_text='Define la naturaleza física del movimiento para reportes', max_length=20),
        ),
        migrations.AddField(
            model_name='registroestibaje',
            name='producto_nombre',
            field=models.CharField(blank=True, help_text='Ej: Torta de Soya Hi Pro', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='registroestibaje',
            name='transportista_nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registroestibaje',
            name='transportista_ruc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tipoestibaje',
            name='accion',
            field=models.CharField(choices=[('CARGA', 'Carga (Salida de Almacén al Camión)'), ('DESCARGA', 'Descarga (Ingreso del Camión al Piso/Almacén)'), ('TRASBORDO', 'Trasbordo (De Camión a Camión directo)'), ('REESTIBA', 'Reestiba (Mover dentro del mismo camión/almacén)'), ('OTRO', 'Otros Servicios')], default='DESCARGA', help_text='Define la naturaleza física del movimiento para reportes', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalregistroestibaje',
            name='tipo_documento',
            field=models.CharField(choices=[('NI', 'Ingreso'), ('GS', 'Salida'), ('OT', 'Otro')], max_length=2),
        ),
        migrations.AlterField(
            model_name='registroestibaje',
            name='tipo_documento',
            field=models.CharField(choices=[('NI', 'Ingreso'), ('GS', 'Salida'), ('OT', 'Otro')], max_length=2),
        ),
    ]
