# Generated by Django 6.0 on 2025-12-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0005_remove_historicalregistroestibaje_transportista_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlmacenPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Permiso de Almacén',
                'verbose_name_plural': 'Permisos de Almacén',
                'permissions': [('can_manage_warehouse', 'Puede gestionar almacén (guías, detalles, kardex, movimientos)'), ('can_view_warehouse', 'Puede ver información de almacén'), ('can_view_warehouse_reports', 'Puede ver reportes de almacén'), ('can_manage_stock', 'Puede gestionar stock y transferencias'), ('can_view_stock', 'Puede ver stock')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
