# Generated by Django 5.2.5 on 2026-01-08 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0006_almacenpermissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='almacenpermissions',
            options={'default_permissions': (), 'managed': False, 'permissions': [('can_manage_warehouse', 'Puede gestionar almacén (guías, detalles, kardex, movimientos)'), ('can_view_warehouse', 'Puede ver información de almacén'), ('can_view_warehouse_reports', 'Puede ver reportes de almacén'), ('can_manage_stock', 'Puede gestionar stock y transferencias'), ('can_view_stock', 'Puede ver stock'), ('can_create_movements', 'Puede crear movimientos de almacén'), ('can_edit_movements', 'Puede editar movimientos de almacén'), ('can_delete_movements', 'Puede eliminar movimientos de almacén'), ('can_create_transfers', 'Puede crear transferencias'), ('can_edit_transfers', 'Puede editar transferencias'), ('can_approve_transfers', 'Puede aprobar transferencias')], 'verbose_name': 'Permiso de Almacén', 'verbose_name_plural': 'Permisos de Almacén'},
        ),
    ]
