# Generated by Django 5.2.5 on 2026-01-09 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0007_alter_almacenpermissions_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregistroestibaje',
            name='almacen',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='almacen.almacen', verbose_name='Almacén de Operación'),
        ),
        migrations.AddField(
            model_name='registroestibaje',
            name='almacen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='estibajes', to='almacen.almacen', verbose_name='Almacén de Operación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalregistroestibaje',
            name='tipo_documento',
            field=models.CharField(choices=[('I', 'Ingreso'), ('S', 'Salida'), ('O', 'Otro')], max_length=2),
        ),
        migrations.AlterField(
            model_name='registroestibaje',
            name='tipo_documento',
            field=models.CharField(choices=[('I', 'Ingreso'), ('S', 'Salida'), ('O', 'Otro')], max_length=2),
        ),
    ]
