# Generated by Django 5.2.5 on 2026-01-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0008_historicalregistroestibaje_almacen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregistroestibaje',
            name='fecha_operacion',
            field=models.DateField(blank=True, null=True, verbose_name='fecha operacion'),
        ),
        migrations.AddField(
            model_name='registroestibaje',
            name='fecha_operacion',
            field=models.DateField(blank=True, null=True, verbose_name='fecha operacion'),
        ),
    ]
